name: artcc_fractar
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.0.0 # He bajado esto a 3.0.0 para asegurar compatibilidad, 3.8.1 podría ser muy alto si no estás en beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Versiones actuales de Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true